TEST_SOURCES = test_dm_complex_sparse.o \
               test_dm_complex.o \
               test_dm_real.o \
               test_dm_real_sparse.o \
               test_ev_complex.o \
               test_ev_complex_sparse.o \
               test_ev_real.o \
               test_ev_real_sparse.o \
               test_rw_real.o \
               test_rw_complex.o

TEST_SOURCES_C = test_dm_complex_c.o \
                 test_dm_real_c.o \
                 test_ev_complex_c.o \
                 test_ev_real_c.o

.PHONY: all test testc checkf checkc

all: test

elsi_test.x: elsi_test.o $(TEST_SOURCES) libelsi.a
	$(FLINKER) $(LDFLAGS) $(FLDFLAGS) -o $@ $^ $(LIBS) $(CUDA_LIB) $(SCALAPACK_LIB) $(CXX_LIB)

elsi_test_rw.x: elsi_test_rw.o $(TEST_SOURCES) libelsi.a
	$(FLINKER) $(LDFLAGS) $(FLDFLAGS) -o $@ $^ $(LIBS) $(CUDA_LIB) $(SCALAPACK_LIB) $(CXX_LIB)

elsi_test_c.x: elsi_test_c.o $(TEST_SOURCES_C) libelsi.a
	$(CLINKER) $(LDFLAGS) $(CLDFLAGS) -o $@ $^ $(LIBS) $(CUDA_LIB) $(SCALAPACK_LIB) $(CXX_LIB)

test_dm_kpt_spin_complex.x: test_dm_kpt_spin_complex.o libelsi.a
	$(FLINKER) $(LDFLAGS) $(FLDFLAGS) -o $@ $^ $(LIBS) $(CUDA_LIB) $(SCALAPACK_LIB) $(CXX_LIB)

test_standard_ev_real.x: test_standard_ev_real.o libelsi.a
	$(FLINKER) $(LDFLAGS) $(FLDFLAGS) -o $@ $^ $(LIBS) $(CUDA_LIB) $(SCALAPACK_LIB) $(CXX_LIB)

elsi_test.o: $(ELSI_DIR)/test/Fortran/elsi_test.f90
	$(MPIFC) $(FFLAGS_I) $(INCS) -c $<

elsi_test_rw.o: $(ELSI_DIR)/test/Fortran/elsi_test_rw.f90
	$(MPIFC) $(FFLAGS_I) $(INCS) -c $<

elsi_test_c.o: $(ELSI_DIR)/test/C/elsi_test_c.c
	$(MPICC) $(CFLAGS_I) $(INCS) -c $<

test_dm_complex.o: $(ELSI_DIR)/test/Fortran/test_dm_complex.f90
	$(MPIFC) $(FFLAGS_I) $(INCS) -c $<

test_dm_complex_sparse.o: $(ELSI_DIR)/test/Fortran/test_dm_complex_sparse.f90
	$(MPIFC) $(FFLAGS_I) $(INCS) -c $<

test_dm_kpt_spin_complex.o: $(ELSI_DIR)/test/Fortran/test_dm_kpt_spin_complex.f90
	$(MPIFC) $(FFLAGS_I) $(INCS) -c $<

test_dm_real.o: $(ELSI_DIR)/test/Fortran/test_dm_real.f90
	$(MPIFC) $(FFLAGS_I) $(INCS) -c $<

test_dm_real_sparse.o: $(ELSI_DIR)/test/Fortran/test_dm_real_sparse.f90
	$(MPIFC) $(FFLAGS_I) $(INCS) -c $<

test_ev_complex.o: $(ELSI_DIR)/test/Fortran/test_ev_complex.f90
	$(MPIFC) $(FFLAGS_I) $(INCS) -c $<

test_ev_complex_sparse.o: $(ELSI_DIR)/test/Fortran/test_ev_complex_sparse.f90
	$(MPIFC) $(FFLAGS_I) $(INCS) -c $<

test_ev_real.o: $(ELSI_DIR)/test/Fortran/test_ev_real.f90
	$(MPIFC) $(FFLAGS_I) $(INCS) -c $<

test_ev_real_sparse.o: $(ELSI_DIR)/test/Fortran/test_ev_real_sparse.f90
	$(MPIFC) $(FFLAGS_I) $(INCS) -c $<

test_standard_ev_real.o: $(ELSI_DIR)/test/Fortran/test_standard_ev_real.f90
	$(MPIFC) $(FFLAGS_I) $(INCS) -c $<

test_rw_complex.o: $(ELSI_DIR)/test/Fortran/test_rw_complex.f90
	$(MPIFC) $(FFLAGS_I) $(INCS) -c $<

test_rw_real.o: $(ELSI_DIR)/test/Fortran/test_rw_real.f90
	$(MPIFC) $(FFLAGS_I) $(INCS) -c $<

test_dm_complex_c.o: $(ELSI_DIR)/test/C/test_dm_complex_c.c
	$(MPICC) $(CFLAGS_I) $(INCS) -c $<

test_dm_real_c.o: $(ELSI_DIR)/test/C/test_dm_real_c.c
	$(MPICC) $(CFLAGS_I) $(INCS) -c $<

test_ev_complex_c.o: $(ELSI_DIR)/test/C/test_ev_complex_c.c
	$(MPICC) $(CFLAGS_I) $(INCS) -c $<

test_ev_real_c.o: $(ELSI_DIR)/test/C/test_ev_real_c.c
	$(MPICC) $(CFLAGS_I) $(INCS) -c $<

test: elsi_test.x elsi_test_rw.x

testc: elsi_test_c.x

checkf: test
	chmod u+x $(ELSI_DIR)/test/make_checkf.sh && $(ELSI_DIR)/test/make_checkf.sh

checkc: testc
	chmod u+x $(ELSI_DIR)/test/make_checkc.sh && $(ELSI_DIR)/test/make_checkc.sh
