gnu-j1-generic:
  script:
    - module purge
    - module load intel-mkl-11.1.1
    - module load intel-mpi-4.1.3
    - module load gcc-7.1
    - module list
    - cp ./make_sys/make.sys-gnu ./make.sys
    - make clean
    - make
    - make check
    - make install

gnu-j8-generic:
  script:
    - module purge
    - module load intel-mkl-11.1.1
    - module load intel-mpi-4.1.3
    - module load gcc-7.1
    - module list
    - cp ./make_sys/make.sys-gnu ./make.sys
    - make clean
    - make -j 8
    - make check
    - make install

intel-j1-debug:
  script:
    - module purge
    - module load intel-mkl-11.1.1
    - module load intel-mpi-4.1.3
    - module load intel-compilers-14.0
    - module list
    - cp ./make_sys/make.sys-timewarp-debug ./make.sys
    - make clean
    - make
    - make check
    - make install

intel-j8-debug:
  script:
    - module purge
    - module load intel-mkl-11.1.1
    - module load intel-mpi-4.1.3
    - module load intel-compilers-14.0
    - module list
    - cp ./make_sys/make.sys-timewarp-debug ./make.sys
    - make clean
    - make -j 8
    - make check
    - make install

intel-j8-gpu:
  script:
    - module purge
    - module load intel-mkl-11.1.1
    - module load intel-mpi-4.1.3
    - module load intel-compilers-14.0
    - module load cuda-8.0
    - module list
    - cp ./make_sys/make.sys-timewarp-gpu ./make.sys
    - make clean
    - make -j 8
    - make check
    - make install

intel-j1-generic:
  script:
    - module purge
    - module load intel-mkl-11.1.1
    - module load intel-mpi-4.1.3
    - module load intel-compilers-14.0
    - module list
    - cp ./make_sys/make.sys-intel ./make.sys
    - make clean
    - make
    - make check
    - make install

intel-j8-generic:
  script:
    - module purge
    - module load intel-mkl-11.1.1
    - module load intel-mpi-4.1.3
    - module load intel-compilers-14.0
    - module list
    - cp ./make_sys/make.sys-intel ./make.sys
    - make clean
    - make -j 8
    - make check
    - make install
