### GNU compilers + OpenMPI + Netlib BLAS, LAPACK, ScaLAPACK ###
gnu:
  script:
    - module purge
    - module load gcc-7.1
    - module load cmake-3.11.3
    - module load openmpi-3.0.0
    - cat ./toolchains/gnu.cmake
    - rm -rf build
    - mkdir build
    - cd build
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/gnu.cmake -DCMAKE_INSTALL_PREFIX=./ ..
    - make -j8
    - ctest --output-on-failure
    - make install

### Intel compilers + MPI + MKL ###
intel:
  script:
    - module purge
    - module load gcc-7.1
    - module load cmake-3.11.3
    - module load intel-2018
    - cat ./toolchains/intel.cmake
    - rm -rf build
    - mkdir build
    - cd build
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/intel.cmake -DCMAKE_INSTALL_PREFIX=./ ..
    - make -j8
    - ctest --output-on-failure
    - make install

### Intel compilers + MPI + MKL + external solver libraries (debug) ###
intel-debug:
  script:
    - module purge
    - module load gcc-7.1
    - module load cmake-3.11.3
    - module load intel-2018
    - cat ./toolchains/intel_debug.cmake
    - rm -rf build
    - mkdir build
    - cd build
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/intel_debug.cmake -DCMAKE_INSTALL_PREFIX=./ ..
    - make -j8
    - ctest --output-on-failure
    - make install
