intel-j1-debug:
  script:
    - module purge
    - module load intel-compilers-14.0
    - module load intel-mpi-4.1.3
    - module list
    - cp ./make_sys/make.sys-timewarp-debug ./make.sys
    - make clean
    - make
    - make check
    - make install

intel-j8-debug:
  script:
    - module purge
    - module load intel-compilers-14.0
    - module load intel-mpi-4.1.3
    - module list
    - cp ./make_sys/make.sys-timewarp-debug ./make.sys
    - make clean
    - make -j 8
    - make check
    - make install

intel-j8-gpu:
  script:
    - module purge
    - module load intel-compilers-14.0
    - module load intel-mpi-4.1.3
    - module load cuda-7.0
    - module list
    - cp ./make_sys/make.sys-timewarp-gpu ./make.sys
    - make clean
    - make -j 8
    - make check
    - make install

intel-j1-generic:
  script:
    - module purge
    - module load intel-compilers-14.0
    - module load intel-mpi-4.1.3
    - module list
    - cp ./make_sys/make.sys-timewarp ./make.sys
    - make clean
    - make
    - make check
    - make install

intel-j8-generic:
  script:
    - module purge
    - module load intel-compilers-14.0
    - module load intel-mpi-4.1.3
    - module list
    - cp ./make_sys/make.sys-timewarp ./make.sys
    - make clean
    - make -j 8
    - make check
    - make install
