variables:
  INSTALL_DIR: "/home/gitlab-runner/ci_tmp_elsi"

### GNU compilers + OpenMPI + Netlib BLAS, LAPACK, ScaLAPACK ###
gnu:
  script:
    - module purge
    - module load gcc-7.1
    - module load cmake-3.8.2
    - module load openmpi-3.0.0
    - cat ./toolchains/gnu.cmake
    - rm -rf build $INSTALL_DIR
    - mkdir build $INSTALL_DIR
    - cd build
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/gnu.cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR ..
    - make -j8
    - ctest --output-on-failure
    - make install

### Intel compilers + MPI + MKL ###
intel:
  script:
    - module purge
    - module load gcc-7.1
    - module load cmake-3.8.2
    - module load intel-compilers-18.0
    - module load intel-mpi-2018.2
    - module load intel-mkl-2018.2
    - cat ./toolchains/intel.cmake
    - rm -rf build $INSTALL_DIR
    - mkdir build $INSTALL_DIR
    - cd build
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/intel.cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR ..
    - make -j8
    - ctest --output-on-failure
    - make install

### Intel compilers + MPI + MKL + external solver libraries (debug) ###
intel-debug:
  script:
    - module purge
    - module load gcc-7.1
    - module load cmake-3.8.2
    - module load intel-compilers-18.0
    - module load intel-mpi-2018.2
    - module load intel-mkl-2018.2
    - cat ./toolchains/intel_debug.cmake
    - rm -rf build $INSTALL_DIR
    - mkdir build $INSTALL_DIR
    - cd build
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/intel_debug.cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR ..
    - make -j8
    - ctest --output-on-failure
    - make install

### Intel compilers + MPI + MKL (shared library) ###
intel-shared:
  script:
    - module purge
    - module load gcc-7.1
    - module load cmake-3.8.2
    - module load intel-compilers-18.0
    - module load intel-mpi-2018.2
    - module load intel-mkl-2018.2
    - cat ./toolchains/intel.cmake
    - rm -rf build $INSTALL_DIR
    - mkdir build $INSTALL_DIR
    - cd build
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/intel.cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR -DBUILD_SHARED_LIBS=ON ..
    - make -j8
    - ctest --output-on-failure
    - make install
