before_script:
  - module purge
  - module load intel-compilers-14.0
  - module load intel-mpi-4.1.3
  - module load m4-1.4.14
  - module load libtool-2.4.6
  - module load autoconf-2.69
  - module load automake-1.14
  - module load cuda-7.0
  - module list

intel-j8-generic:
  script:
    - cp ./MAKE_SYS/make.sys-timewarp-intel ./make.sys
    - make -j 8 -f Makefile.elsi

intel-j1-generic:
  script:
    - cp ./MAKE_SYS/make.sys-timewarp-intel ./make.sys
    - make -f Makefile.elsi

intel-j8-gpu:
  script:
    - cp ./MAKE_SYS/make.sys-timewarp-intel-cuda ./make.sys
    - make -j 8 -f Makefile.elsi
