before_script:
  - module purge
  - module load intel-compilers-14.0
  - module load intel-mpi-4.1.3
  - module load m4-1.4.14
  - module load libtool-2.4.6
  - module load autoconf-2.69
  - module load automake-1.14
  - module load cuda-7.0
  - module list

intel-j8-gpu:
  script:
    - cp ./make_sys/make.sys-timewarp-gpu ./make.sys
    - make clean
    - make -j 8
    - make check
    - make install

intel-j1-generic:
  script:
    - cp ./make_sys/make.sys-timewarp ./make.sys
    - make clean
    - make
    - make check
    - make install

intel-j8-generic:
  script:
    - cp ./make_sys/make.sys-timewarp ./make.sys
    - make clean
    - make -j 8
    - make check
    - make install
