before_script:
  - module use /home/wy29/opt/modulefiles
  - module use /home/yy244/yy_modules
  - module purge
  - module load gcc-7.5.0
  - module load cmake_3.20.5
  - export OMP_NUM_THREADS=1

variables:
  CI_DEBUG_TRACE: "true"

### GNU compilers + OpenMPI + Netlib BLAS, LAPACK, ScaLAPACK ###
gnu:
  script:
    - module load openmpi-4.1.0
    - cat ./toolchains/gnu.cmake
    - rm -rf build
    - mkdir build
    - cd build
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/gnu.cmake ..
    - make -j4
    - ctest --output-on-failure

### NVIDIA HPC SDK (20.7) ###
nvhpc:
  script:
    - module unload gcc-7.5.0
    - module load gcc-7.5
    - module load glibc-2.14
    - module load nvhpc_yy/20.7
    - module list
    - cat ./toolchains/nvhpc.cmake
    - export LD_PRELOAD=/home/yy244/compilers/gcc_install/7.5/lib64/libstdc++.so.6
    - rm -rf build
    - mkdir build
    - cd build
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/nvhpc.cmake ..
    - make -j4
    - ctest --output-on-failure

### Intel compilers + MPI + MKL ###
intel:
  script:
    - module load intel-compilers-2018.4
    - module load intel-mpi-2018.4
    - module load intel-mkl-2018.4
    - export MKL_DYNAMIC=FALSE
    - export MKL_NUM_THREADS=1
    - cat ./toolchains/intel.cmake
    - rm -rf build
    - mkdir build
    - cd build
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/intel.cmake ..
    - make -j4
    - ctest --output-on-failure

### Intel compilers + MPI + MKL (shared library) ###
intel-shared:
  script:
    - module load intel-compilers-2018.4
    - module load intel-mpi-2018.4
    - module load intel-mkl-2018.4
    - export MKL_DYNAMIC=FALSE
    - export MKL_NUM_THREADS=1
    - cat ./toolchains/intel.cmake
    - rm -rf build
    - mkdir build
    - cd build
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/intel.cmake -DBUILD_SHARED_LIBS=ON ..
    - make -j4
    - ctest --output-on-failure

### Intel compilers + MPI + MKL + external solver libraries (debug) ###
intel-debug:
  script:
    - module load intel-compilers-2018.4
    - module load intel-mpi-2018.4
    - module load intel-mkl-2018.4
    - export MKL_DYNAMIC=FALSE
    - export MKL_NUM_THREADS=1
    - cat ./toolchains/intel_debug.cmake
    - rm -rf build
    - mkdir build
    - cd build
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/intel_debug.cmake ..
    - make -j4
    - ctest --output-on-failure
