before_script:
  - module use /home/wy29/opt/modulefiles
  - module purge
  - module load gcc-7.4.0
  - module load cmake-3.0.2

### GNU compilers + OpenMPI + Netlib BLAS, LAPACK, ScaLAPACK ###
gnu:
  script:
    - module load openmpi-4.0.1
    - cat ./toolchains/gnu.cmake
    - rm -rf build
    - mkdir build
    - cd build
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/gnu.cmake ..
    - make -j8
    - ctest --output-on-failure

### Intel compilers + MPI + MKL ###
intel:
  script:
    - module load intel-compilers-18.0
    - module load intel-mpi-2018.2
    - module load intel-mkl-2018.2
    - cat ./toolchains/intel.cmake
    - rm -rf build
    - mkdir build
    - cd build
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/intel.cmake ..
    - make -j8
    - ctest --output-on-failure

### Intel compilers + MPI + MKL + external solver libraries (debug) ###
intel-debug:
  script:
    - module load intel-compilers-18.0
    - module load intel-mpi-2018.2
    - module load intel-mkl-2018.2
    - cat ./toolchains/intel_debug.cmake
    - rm -rf build
    - mkdir build
    - cd build
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/intel_debug.cmake ..
    - make -j8
    - ctest --output-on-failure

### Intel compilers + MPI + MKL (shared library) ###
intel-shared:
  script:
    - module load intel-compilers-18.0
    - module load intel-mpi-2018.2
    - module load intel-mkl-2018.2
    - cat ./toolchains/intel.cmake
    - rm -rf build
    - mkdir build
    - cd build
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/intel.cmake -DBUILD_SHARED_LIBS=ON ..
    - make -j8
    - ctest --output-on-failure
