gnu-j1-generic:
  script:
    - module purge
    - module load intel-mkl-11.1.1
    - module load intel-mpi-4.1.3
    - module load gcc-7.1
    - module list
    - cp ./make_sys/make.sys-gnu ./make.sys
    - make clean
    - make
    - make check
    - make install

gnu-j8-generic:
  script:
    - module purge
    - module load intel-mkl-11.1.1
    - module load intel-mpi-4.1.3
    - module load gcc-7.1
    - module list
    - cp ./make_sys/make.sys-gnu ./make.sys
    - make clean
    - make -j 8
    - make check
    - make install

pgi-j1-generic:
  script:
    - module purge
    - module load intel-mkl-11.1.1
    - module load intel-mpi-4.1.3
    - module load pgi-17.4
    - module list
    - cp ./make_sys/make.sys-timewarp-pgi ./make.sys
    - make clean
    - make
    - make check
    - make install

pgi-j8-generic:
  script:
    - module purge
    - module load intel-mkl-11.1.1
    - module load intel-mpi-4.1.3
    - module load pgi-17.4
    - module list
    - cp ./make_sys/make.sys-timewarp-pgi ./make.sys
    - make clean
    - make -j 8
    - make check
    - make install

intel-j1-debug:
  script:
    - module purge
    - module load intel-mkl-11.1.1
    - module load intel-mpi-4.1.3
    - module load intel-compilers-14.0
    - module list
    - cp ./make_sys/make.sys-timewarp-debug ./make.sys
    - make clean
    - make
    - make check
    - make install

intel-j8-debug:
  script:
    - module purge
    - module load intel-mkl-11.1.1
    - module load intel-mpi-4.1.3
    - module load intel-compilers-14.0
    - module list
    - cp ./make_sys/make.sys-timewarp-debug ./make.sys
    - make clean
    - make -j 8
    - make check
    - make install

intel-j8-gpu:
  script:
    - module purge
    - module load intel-mkl-11.1.1
    - module load intel-mpi-4.1.3
    - module load intel-compilers-14.0
    - module load cuda-8.0
    - module list
    - cp ./make_sys/make.sys-timewarp-gpu ./make.sys
    - make clean
    - make -j 8
    - make check
    - make install

intel-j1-generic:
  script:
    - module purge
    - module load intel-mkl-11.1.1
    - module load intel-mpi-4.1.3
    - module load intel-compilers-14.0
    - module list
    - cp ./make_sys/make.sys-intel ./make.sys
    - make clean
    - make
    - make check
    - make install

intel-j8-generic:
  script:
    - module purge
    - module load intel-mkl-11.1.1
    - module load intel-mpi-4.1.3
    - module load intel-compilers-14.0
    - module list
    - cp ./make_sys/make.sys-intel ./make.sys
    - make clean
    - make -j 8
    - make check
    - make install

# We do not run make check for external linkage.  Not our circus, not our monkey.
# We've also marked this test as optional, as it is acceptable for this test to 
# break during normal development work, but nevertheless we should know what 
# commits broke it and when.
intel-j8-external-linkage:
  script:
    - module purge
    - module load intel-mkl-11.1.1
    - module load intel-mpi-4.1.3
    - module load intel-compilers-14.0
    - module list
    - cp ./make_sys/make.sys-external-linkage ./make.sys
    - make clean
    - make -j 8
    - make install
  allow_failure: true
