gnu-j1-generic:
  script:
    - module purge
    - module load gcc-7.1
    - cp /home/wy29/elsi_make_check/check_gnu ./make.sys
    - make
    - make install
    - make clean

gnu-j8-generic:
  script:
    - module purge
    - module load gcc-7.1
    - cp /home/wy29/elsi_make_check/check_gnu ./make.sys
    - make -j 8
    - make check
    - make checkc
    - make install
    - make clean

pgi-j1-generic:
  script:
    - module purge
    - module load gcc-7.1
    - module load pgi-17.4
    - cp /home/wy29/elsi_make_check/check_pgi ./make.sys
    - make
    - make install
    - make clean

pgi-j8-generic:
  script:
    - module purge
    - module load gcc-7.1
    - module load pgi-17.4
    - cp /home/wy29/elsi_make_check/check_pgi ./make.sys
    - make -j 8
    - make check
    - make checkc
    - make install
    - make clean

intel-j1-debug:
  script:
    - module purge
    - module load gcc-7.1
    - cp /home/wy29/elsi_make_check/check_intel_debug ./make.sys
    - make
    - make install
    - make clean

intel-j8-debug:
  script:
    - module purge
    - module load gcc-7.1
    - cp /home/wy29/elsi_make_check/check_intel_debug ./make.sys
    - make -j 8
    - make check
    - make checkc
    - make install
    - make clean

intel-j8-gpu:
  script:
    - module purge
    - module load gcc-7.1
    - module load cuda-8.0
    - cp /home/wy29/elsi_make_check/check_intel_gpu ./make.sys
    - make -j 8
    - make check
    - make install
    - make clean

intel-j1-generic:
  script:
    - module purge
    - module load gcc-7.1
    - cp /home/wy29/elsi_make_check/check_intel ./make.sys
    - make
    - make install
    - make clean

intel-j8-generic:
  script:
    - module purge
    - module load gcc-7.1
    - cp /home/wy29/elsi_make_check/check_intel ./make.sys
    - make -j 8
    - make check
    - make checkc
    - make install
    - make clean

# We do not run make check for external linkage.  Not our circus, not our monkey.
# We've also marked this test as optional, as it is acceptable for this test to
# break during normal development work, but nevertheless we should know what
# commits broke it and when.
intel-j8-external-linkage:
  script:
    - module purge
    - module load gcc-7.1
    - cp /home/wy29/elsi_make_check/check_external ./make.sys
    - make -j 8
    - make install
    - make clean
  allow_failure: true
