# SIPs Makefile used in ELSI.
# Feb 9, 2018

.PHONY: all install

all: m_qetsc.o

m_qetsc.o: $(SIPS_DIR)/src/m_qetsc.F90
	$(MPIFC) $(FFLAGS_S) $(SLEPC_INC) $(PETSC_INC) -c $<

libqetsc.a: m_qetsc.o
	$(ARCHIVE) $(ARCHIVEFLAGS) $@ m_qetsc.o
	$(RANLIB) $@

install: libqetsc.a
	cp $(BUILD_DIR)/SIPS/*.a $(LIB_DIR)
	cp $(BUILD_DIR)/SIPS/*.mod $(INC_DIR)
