# SIPs Makefile used in ELSI.
# Feb 9, 2018

.PHONY: all

all: libqetsc.a

m_qetsc.o: $(SIPS_DIR)/src/m_qetsc.F90
	$(MPIFC) $(FFLAGS_S) $(SLEPC_INC) $(PETSC_INC) -c $<

libqetsc.a: m_qetsc.o
	$(ARCHIVE) $(ARCHIVEFLAGS) $@ m_qetsc.o
	$(RANLIB) $@
