# http://stackoverflow.com/a/19578320

STRING(ASCII 27 Esc)
SET(COLORRESET  "${Esc}[m")
SET(COLORBOLD   "${Esc}[1m")
SET(RED         "${Esc}[31m")
SET(GREEN       "${Esc}[32m")
SET(YELLOW      "${Esc}[33m")
SET(BLUE        "${Esc}[34m")
SET(MAGENTA     "${Esc}[35m")
SET(CYAN        "${Esc}[36m")
SET(WHITE       "${Esc}[37m")
SET(BOLDRED     "${Esc}[1;31m")
SET(BOLDGREEN   "${Esc}[1;32m")
SET(BOLDYELLOW  "${Esc}[1;33m")
SET(BOLDBLUE    "${Esc}[1;34m")
SET(BOLDMAGENTA "${Esc}[1;35m")
SET(BOLDCYAN    "${Esc}[1;36m")
SET(BOLDWHITE   "${Esc}[1;37m")
