IF(FORTJSON_INC AND FORTJSON_LIB)
  MESSAGE(STATUS "Using external FortJSON")
  MESSAGE(STATUS "${GREEN}FORTJSON_LIB${COLORRESET}: ${FORTJSON_LIB}")
  MESSAGE(STATUS "${GREEN}FORTJSON_INC${COLORRESET}: ${FORTJSON_INC}")

  FOREACH(usr_lib ${FORTJSON_LIB})
    IF(NOT EXISTS ${usr_lib})
      MESSAGE(FATAL_ERROR "${MAGENTA}User provided FortJSON library not found: ${usr_lib}${COLORRESET}")
    ENDIF()
  ENDFOREACH()

  FOREACH(usr_dir ${FORTJSON_INC})
    IF(NOT EXISTS ${usr_dir})
      MESSAGE(FATAL_ERROR "${MAGENTA}User provided FortJSON include path not found: ${usr_dir}${COLORRESET}")
    ENDIF()
  ENDFOREACH()

  SET(FORTJSON_FOUND TRUE)
ELSE()
  MESSAGE(STATUS "Enabling internal FortJSON")

  SET(FORTJSON_FOUND FALSE)
ENDIF()
