IF(PTSCOTCH_INC AND PTSCOTCH_LIB)
  MESSAGE(STATUS "Using external PT-SCOTCH")
  MESSAGE(STATUS "${GREEN}PTSCOTCH_LIB${COLORRESET}: ${PTSCOTCH_LIB}")
  MESSAGE(STATUS "${GREEN}PTSCOTCH_INC${COLORRESET}: ${PTSCOTCH_INC}")

  FOREACH(usr_lib ${PTSCOTCH_LIB})
    IF(NOT EXISTS ${usr_lib})
      MESSAGE(FATAL_ERROR "${MAGENTA}User provided PT-SCOTCH library not found: ${usr_lib}${COLORRESET}")
    ENDIF()
  ENDFOREACH()

  FOREACH(usr_dir ${PTSCOTCH_INC})
    IF(NOT EXISTS ${usr_dir})
      MESSAGE(FATAL_ERROR "${MAGENTA}User provided PT-SCOTCH include path not found: ${usr_dir}${COLORRESET}")
    ENDIF()
  ENDFOREACH()

  SET(PTSCOTCH_FOUND TRUE)
ELSE()
  MESSAGE(STATUS "Enabling internal PT-SCOTCH")

  ADD_SUBDIRECTORY(${PROJECT_SOURCE_DIR}/external/SCOTCH)

  SET(PTSCOTCH_FOUND FALSE)
ENDIF()
