INCLUDE(ptscotch)

SET(SUPERLU_LIB $ENV{SUPERLU_LIB})
SET(SUPERLU_INC $ENV{SUPERLU_INC})

IF(SUPERLU_INC AND SUPERLU_LIB)
  MESSAGE(STATUS "Using external SuperLU_DIST")
  MESSAGE(STATUS "  SUPERLU_LIB: ${SUPERLU_LIB}")
  MESSAGE(STATUS "  SUPERLU_INC: ${SUPERLU_INC}")

  FOREACH(usr_lib ${SUPERLU_LIB})
    IF(NOT EXISTS ${usr_lib})
      MESSAGE(FATAL_ERROR "User provided SuperLU_DIST library not found: ${usr_lib}")
    ENDIF()
  ENDFOREACH()

  FOREACH(usr_dir ${SUPERLU_INC})
    IF(NOT EXISTS ${usr_dir})
      MESSAGE(FATAL_ERROR "User provided SuperLU_DIST include path not found: ${usr_dir}")
    ENDIF()

    SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -I${usr_dir}")
    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -I${usr_dir}")
  ENDFOREACH()

  SET(EXTERNAL_SUPERLU TRUE)
ELSE()
  MESSAGE(STATUS "Enabling internal SuperLU_DIST")

  SET(EXTERNAL_SUPERLU FALSE)
ENDIF()
